name: Main Push
on:
  push:
    paths: ["src/**", ".github/workflows/push-main.yml", "package.json"] # Trigger the action only when files change in the folders defined here
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.0.2
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install (PNPM) 🔧
        run: pnpm install
      - name: Generate Type Definitions (TSC)
        run: pnpm types:gen
      - name: Unit Test (JEST)
        run:  pnpm unit:test:coverage
      - name: Build Storybook
        run: pnpm run storybook:build
      - name: Deploy Storybook 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main # The branch the action should deploy to.
          FOLDER: docs-build # The folder that the build-storybook script generates files.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          TARGET_FOLDER: docs # The folder that we serve our Storybook files from
